# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sun/Vivado2019/nscscc/func-submit/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/btb_ram/btb_ram.xci
# IP: The module: 'btb_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sun/Vivado2019/nscscc/func-submit/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/btb_ram/btb_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'btb_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/sun/Vivado2019/nscscc/func-submit/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/btb_ram/btb_ram.xci
# IP: The module: 'btb_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sun/Vivado2019/nscscc/func-submit/soc_verify/soc_axi/run_vivado/project/loongson.srcs/sources_1/ip/btb_ram/btb_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'btb_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
